### ISSUE TITLE
Jason seems to be faster on recent Elixir version (1.14)

### ISSUE THREAD

**Issue by mindreframer** [benhaney/Jsonrs#13]
System: 
```
Operating System: macOS
CPU Information: Apple M1
Number of Available Cores: 8
Available memory: 16 GB
Elixir 1.14.0
Erlang 25.0.4
```

```elixir
small_list = Enum.to_list(1..100)
big_list = Enum.to_list(1..10_000)
small_map = Enum.map(small_list, fn(x)-> {"key#{x}", x} end) |> Enum.into(%{})
big_map = Enum.map(big_list, fn(x)-> {"key#{x}", x} end) |> Enum.into(%{})


Benchee.run(
  %{
    "jsonrs.encode! - small" => fn -> Jsonrs.encode!(small_map) end,
    "Jason.encode! - small" => fn -> Jason.encode!(small_map) end
  }
)

Benchee.run(
  %{
    "jsonrs.encode! - big" => fn -> Jsonrs.encode!(big_map) end,
    "Jason.encode! - big" => fn -> Jason.encode!(big_map) end
  }
)

```

RESULT: 
```
Operating System: macOS
CPU Information: Apple M1
Number of Available Cores: 8
Available memory: 16 GB
Elixir 1.14.0
Erlang 25.0.4

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 5 s
memory time: 0 ns
reduction time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 14 s

Benchmarking Jason.encode! - small ...
Benchmarking jsonrs.encode! - small ...

Name                             ips        average  deviation         median         99th %
Jason.encode! - small        84.74 K       11.80 μs    ±36.67%       11.33 μs       16.83 μs
jsonrs.encode! - small       25.35 K       39.45 μs    ±56.39%       35.08 μs       94.58 μs

Comparison:
Jason.encode! - small        84.74 K
jsonrs.encode! - small       25.35 K - 3.34x slower +27.65 μs
Operating System: macOS
CPU Information: Apple M1
Number of Available Cores: 8
Available memory: 16 GB
Elixir 1.14.0
Erlang 25.0.4

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 5 s
memory time: 0 ns
reduction time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 14 s

Benchmarking Jason.encode! - big ...
Benchmarking jsonrs.encode! - big ...

Name                           ips        average  deviation         median         99th %
Jason.encode! - big         642.38        1.56 ms    ±10.56%        1.50 ms        1.93 ms
jsonrs.encode! - big        478.25        2.09 ms     ±6.31%        2.07 ms        2.36 ms

Comparison:
Jason.encode! - big         642.38
jsonrs.encode! - big        478.25 - 1.34x slower +0.53 ms
```

Statements from the readme file seem not to reflect those recent developments. Maybe adding a disclaimer about differences on different Erlang VMs / Elixir versions would help? 

Cheers and thanks for this library!

**Comment by benhaney** [comment]
This is a valid concern, but a very poor benchmark. Despite one of the inputs being named "big," they are both very small, coming out to a fraction of a megabyte of output at most. The data is also extremely flat and simple, which isn't representative of real world data at all. With data this small and simple, the performance of your JSON library largely doesn't matter and isn't ever going to be your bottleneck outside of crafted microbenchmarks. I understand that the statements in the readme sound rather confident and sweeping ("Jsonrs _is_ faster" rather than "Jsonrs is nearly always faster in cases that matter but can sometimes be slower in crafted scenarios that never matter in the real world"), but I think it's fair to assume a bit of understanding in the mind of the reader that these statements aren't universal absolutes and have a relevant domain that they are generally true in.
For small cases like these specifically, any JSON library will probably perform somewhat similarly as any other, and nobody working with this data would be running into performance issues caused by their JSON library of choice, so I'd never expect them to find their way here in the first place to read the statements in the readme. On top of that, simple data like this is what Jsonrs's lean mode is for, which should perform better than the fat default mode of Jsonrs that you're testing.

Here is your benchmark, refactored into a single benchee run, with Jsonrs running in lean mode as an additional function under test, and with memory stats

```elixir
small_map = Map.new(1..100, &{"key#{&1}", &1})
big_map = Map.new(1..10_000, &{"key#{&1}", &1})

Benchee.run(
  %{
    "Jsonrs.encode!" => &Jsonrs.encode!/1,
    "Jsonrs_lean.encode!" => &Jsonrs.encode!(&1, lean: true),
    "Jason.encode!" => &Jason.encode!/1
  },
  memory_time: 0.01,
  inputs: %{"small" => small_map, "big" => big_map}
)
```

And here is how it runs on my machine:

```
Operating System: macOS
CPU Information: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Number of Available Cores: 4
Available memory: 8 GB
Elixir 1.14.2
Erlang 25.1.2

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 5 s
memory time: 10 ms
inputs: big, small

[...]

##### With input big #####
Name                          ips        average  deviation         median         99th %
Jsonrs_lean.encode!        505.67        1.98 ms     ±6.47%        1.94 ms        2.72 ms
Jason.encode!              244.46        4.09 ms    ±17.35%        3.89 ms        6.13 ms
Jsonrs.encode!             213.51        4.68 ms     ±6.74%        4.59 ms        6.14 ms

Comparison: 
Jsonrs_lean.encode!        505.67
Jason.encode!              244.46 - 2.07x slower +2.11 ms
Jsonrs.encode!             213.51 - 2.37x slower +2.71 ms

Memory usage statistics:

Name                   Memory usage
Jsonrs_lean.encode!      0.00011 MB
Jsonrs.encode!              0.84 MB - 7346.87x memory usage +0.84 MB
Jason.encode!               1.68 MB - 14674.33x memory usage +1.68 MB

**All measurements for memory usage were the same**

##### With input small #####
Name                          ips        average  deviation         median         99th %
Jsonrs_lean.encode!       38.24 K       26.15 μs    ±35.02%       24.71 μs       56.14 μs
Jason.encode!             35.14 K       28.46 μs   ±105.13%       24.77 μs       67.04 μs
Jsonrs.encode!            21.78 K       45.92 μs    ±27.02%       43.08 μs       89.09 μs

Comparison: 
Jsonrs_lean.encode!       38.24 K
Jason.encode!             35.14 K - 1.09x slower +2.31 μs
Jsonrs.encode!            21.78 K - 1.76x slower +19.76 μs

Memory usage statistics:

Name                   Memory usage
Jsonrs_lean.encode!        0.117 KB
Jsonrs.encode!              7.96 KB - 67.93x memory usage +7.84 KB
Jason.encode!              15.52 KB - 132.40x memory usage +15.40 KB

**All measurements for memory usage were the same**
```

As you can see, Jsonrs in lean mode tends to run faster for me than both normal Jsonrs and Jason in this benchmark by a good margin, and the runtime difference between non-lean Jsonrs and Jason seems to be much smaller on my machine for this benchmark than yours. The memory differences also skew heavily in favor of Jsonrs, but that's not necessarily relevant to speed comparisons. Either way, I maintain that this benchmark isn't representative of useful real-world performance, and better benchmarks using real-world data should be focused on instead.

And hell, let's just do that. Jason has its own [corpus of real-world data](https://github.com/michalmuskala/jason/tree/master/bench/data) that it benchmarks against, and we can just run [Jason's own benchmarks](https://github.com/michalmuskala/jason/blob/master/bench/encode.exs) to compare it against Jsonrs after setting the `encode_jobs` as such:

```elixir
encode_jobs = %{
  "Jason"  => &Jason.encode/1,
  "Jsonrs" => &Jsonrs.encode/1,
  "Jsonrs (lean)" => &Jsonrs.encode(&1, lean: true)
}
```

Here are benchee graphs comparing runtime and memory usage of Jason, Jsonrs, and Jsonrs in lean mode, ordered from smallest to largest benchmark data size (with the last three being the only ones I would really consider "big"):
<img src="https://user-images.githubusercontent.com/31331498/201551365-56fb33a4-7ab9-420e-89ff-849ca2830375.png" width=50%><img src="https://user-images.githubusercontent.com/31331498/201551373-67fdad8b-f5eb-4761-9869-d635d0aa1ac7.png" width=50%>
<img src="https://user-images.githubusercontent.com/31331498/201551881-da9b1008-e770-401d-ad48-dec2cdf4e185.png" width=50%><img src="https://user-images.githubusercontent.com/31331498/201551884-138bbe45-26a7-4b4b-a344-76a79fdfa0ab.png" width=50%>
<img src="https://user-images.githubusercontent.com/31331498/201551945-7bc7c6eb-cbff-410b-9df9-6932f23907c5.png" width=50%><img src="https://user-images.githubusercontent.com/31331498/201551955-16c6f904-ee84-477a-be53-c86593ea347b.png" width=50%>
<img src="https://user-images.githubusercontent.com/31331498/201552025-3bdc8a27-180f-48b1-9551-aa42b2b41266.png" width=50%><img src="https://user-images.githubusercontent.com/31331498/201552026-dd985ff4-ce4c-4771-b590-42a12de4b829.png" width=50%>
<img src="https://user-images.githubusercontent.com/31331498/201552062-8425a304-8171-4f30-a5cf-cf56c06e335a.png" width=50%><img src="https://user-images.githubusercontent.com/31331498/201552063-8546a23e-5fab-445b-97e8-75cf549dab7e.png" width=50%>
<img src="https://user-images.githubusercontent.com/31331498/201552116-c45639c6-0f8e-40e7-bc7b-3c30faba3e00.png" width=50%><img src="https://user-images.githubusercontent.com/31331498/201552119-31c4a2a1-e8fc-4dd6-99e5-8c28daf135df.png" width=50%>
<img src="https://user-images.githubusercontent.com/31331498/201552146-7d5f9ba3-4452-4904-87ad-976dc9385866.png" width=50%><img src="https://user-images.githubusercontent.com/31331498/201552149-642b3b53-b579-4b25-9263-84c35b8f1032.png" width=50%>
<img src="https://user-images.githubusercontent.com/31331498/201552178-fe5ea0f4-6bac-43df-a34c-b7e1add9b1cf.png" width=50%><img src="https://user-images.githubusercontent.com/31331498/201552184-ef9d663f-88f0-4589-a0d6-1505fa8d2f70.png" width=50%>

Since I first tested Jason, it has improved quite a bit in runtime performance (and not at all in memory usage). But it's still pretty solidly outperformed by Jsonrs in every single test of real world data, so I don't think the claims in the readme particularly need to be changed. The issue is very nuanced though, so I'd love to hear if you have further opinions around how claims should be worded or phrased.

**Comment by mindreframer** [comment]
@benhaney Wow, that is one elaborate response! 😃 I missed out the `lean` option and yes, on my machine Jsonrs now is much faster than Jason! Quite exciting. And yes, the payloads do not represent real-world workloads, I just wanted to have a quick feeling how Jsonrc performs. 

You convinced me :) Thanks for the quick answer.
