### ISSUE TITLE
can't decode a charlist

### ISSUE THREAD

**Issue by ndrean** [benhaney/Jsonrs#23]
I receive a payload as a charlist from `:httpc`, so I need to convert it into a string to `Jsonrs.decode!` it.  The library `Jason` can do it without the string conversion. Is it worth using Jsonrs when I have this kind of conversion to do?

**Comment by benhaney** [comment]
Good catch. I'll toss an `IO.iodata_to_binary` into `decode!` like Jason does.

**Comment by ndrean** [comment]
You didn't push a new version, did you?

**Comment by benhaney** [comment]
I didn't cut a release to publish on Hex, no. I've been away for a few days and didn't want to release a new version for a small untested feature since I wouldn't be able to respond to any bugs it might cause.

Have you tried it out yet? Is it solving your problem and not causing any issues? I'll be happy to cut an official release if it seems to be working fine.

**Comment by ndrean** [comment]
Probably only `:httpc` requires this addition since it uses charlist and not binary and outputs a charlist. Say you develop a package and want minimal dependencies and make small HTTP requests and decode the result, you may want this.

I believe a simple test in the terminal demonstrates it works

```elixir
Mix.install([:jsonrs]);
{:ok, {{_, 200, _}, _, body}} = :httpc.request(:get, {~c"https://jsonplaceholder.typicode.com/posts", []},[], []);
to_string(body) |> Jsonrs.decode!
```

I only used `Jsonrs` when I query for npm packages, along with Finch (streaming this paginated endpoint) so it works as it is. If I add `IO.iodata_to_binary()` before decoding, it also works, so I believe it is ok.
