### ISSUE TITLE
Benchmarks vs OTP 27 json module

### ISSUE THREAD

**Issue by axelson** [benhaney/Jsonrs#27]
Hi, is it possible to benchmark jsonrs vs the new json module that's been added in OTP 27? I'm curious how they'll stack up!

**Comment by dlindenkreuz** [comment]
I just added Jsonrs and the new Elixir.JSON module to the benchmark suite to the Jason repository: https://github.com/michalmuskala/jason/pull/198

Screenshots from a quick run on my machine (`json` refers to Erlang's json module, available since OTP 27):
Elixir's new JSON module adds a negligible overhead to Erlang's `json` which it calls under the hood.

<img width="685" alt="Screenshot 2024-12-20 at 11 27 42" src="https://github.com/user-attachments/assets/17fca765-c0a9-48c2-94ec-ca108d72a6af" />
<img width="673" alt="Screenshot 2024-12-20 at 11 27 53" src="https://github.com/user-attachments/assets/0e9fee85-3b01-41e5-ae82-ce86458d2f19" />

**Comment by axelson** [comment]
Nice! Thank you for running them. Is the benchmark script somewhere in the git repo? I'm having trouble finding it.

**Comment by dlindenkreuz** [comment]
It’s not in this repo but in the Jason repo: https://github.com/michalmuskala/jason/tree/f1aa12ba6949dd90f6b45519d13699a3e9829f55/bench

(link leads to my PR branch)

**Comment by axelson** [comment]
Ah, got it. Thank you!

**Comment by acrogenesis** [comment]
so jsonrs is faster than "native" json 😮 you should definitely add this on the readme.
