### ISSUE TITLE
Performance for 1k json

### ISSUE THREAD

**Issue by romaluca** [benhaney/Jsonrs#3]
Is possible have performance also for a 1k json?

Thanks

**Comment by benhaney** [comment]
At 1K there is not much difference in the speed of different libraries.

At this size, it generally only takes around 100μs or less to do an encode, so this benchmark isn't particularly useful because of the high margin of error.

![1K iterations per second](https://user-images.githubusercontent.com/31331498/85367076-28538600-b4ee-11ea-9a58-97d28c2a7db8.png)


Memory usage at least is reliably consistent between runs, but also probably doesn't matter much at this small of a scale.

![1K memory usage](https://user-images.githubusercontent.com/31331498/85366317-b75f9e80-b4ec-11ea-8938-19013c607873.png)

If you go even smaller than this, you can find examples that will be consistently faster with Jason/Poison than with Jsonrs as the extremely small fixed time cost of jumping into a Rustler NIF overtakes the cost of actually performing the encode.

**Comment by romaluca** [comment]
Ok Thanks!
